[package]
name = "projup"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.47", features = ["cargo", "derive"] }
colored = "3.0.0"
directories = "6.0.0"
git2 = "0.20.2"
log = "0.4.28"
thiserror = "2.0.16"
